name: damt  
description: Command-line application to manage a database of acronyms.
version: 0.3.4
homepage: https://github.com/wiremoons/damt

platforms:
  linux:
  windows:
  macos:

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.3.1
  dav: ^0.2.0
  http: ^1.0.0
  intl: ^0.18.1
  path: ^1.8.3
  sqlite3: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
