name: damt  
description: Command-line application to manage a database of acronyms.
version: 0.1.3
homepage: https://github.com/wiremoons/damt

platforms:
  linux:
  windows:
  macos:

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  args: ^2.3.1
  dav: ^0.1.3
  http: ^1.0.0
  path: ^1.8.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
